version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diabetes_mvp_django
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8350 --workers 3 --timeout 120
    ports:
      - "8350:8350"
    volumes:
      - .:/app
    restart: always